# This contains the global configuration of your component.
# BABYLON_ENV:
#    jid: your.component.jid
#    password: your.component.password
#    host: host on which the XMPP server is running
#    port: port to which your component should connect
#    application_type: client | component (by default it is component and we strongly discourage any client application in production)

development:
    jid: component.server.com
    password: password
    host: localhost
    port: 5278

test:
    jid: component.server.com
    password: password
    host: localhost
    port: 5278
        
production:
    jid: component.server.com
    password: password
    host: localhost
    port: 5278
